# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andreas/EPITECH_PROJECT/OOP/Arcade/MIRROR-B-OOP-400-NAN-4-1-arcade-andreas.le-tanter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andreas/EPITECH_PROJECT/OOP/Arcade/MIRROR-B-OOP-400-NAN-4-1-arcade-andreas.le-tanter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/EPITECH_PROJECT/OOP/Arcade/MIRROR-B-OOP-400-NAN-4-1-arcade-andreas.le-tanter/CMakeFiles /home/andreas/EPITECH_PROJECT/OOP/Arcade/MIRROR-B-OOP-400-NAN-4-1-arcade-andreas.le-tanter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andreas/EPITECH_PROJECT/OOP/Arcade/MIRROR-B-OOP-400-NAN-4-1-arcade-andreas.le-tanter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arcade

# Build rule for target.
arcade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arcade
.PHONY : arcade

# fast build rule for target.
arcade/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/build
.PHONY : arcade/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named ncurses

# Build rule for target.
ncurses: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncurses
.PHONY : ncurses

# fast build rule for target.
ncurses/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/build
.PHONY : ncurses/fast

#=============================================================================
# Target rules for targets named sfml

# Build rule for target.
sfml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml
.PHONY : sfml

# fast build rule for target.
sfml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml.dir/build.make CMakeFiles/sfml.dir/build
.PHONY : sfml/fast

#=============================================================================
# Target rules for targets named sdl

# Build rule for target.
sdl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl
.PHONY : sdl

# fast build rule for target.
sdl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl.dir/build.make CMakeFiles/sdl.dir/build
.PHONY : sdl/fast

#=============================================================================
# Target rules for targets named graphicals

# Build rule for target.
graphicals: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphicals
.PHONY : graphicals

# fast build rule for target.
graphicals/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphicals.dir/build.make CMakeFiles/graphicals.dir/build
.PHONY : graphicals/fast

#=============================================================================
# Target rules for targets named pacman

# Build rule for target.
pacman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pacman
.PHONY : pacman

# fast build rule for target.
pacman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/build
.PHONY : pacman/fast

#=============================================================================
# Target rules for targets named snake

# Build rule for target.
snake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snake
.PHONY : snake

# fast build rule for target.
snake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/build
.PHONY : snake/fast

#=============================================================================
# Target rules for targets named games

# Build rule for target.
games: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 games
.PHONY : games

# fast build rule for target.
games/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/games.dir/build.make CMakeFiles/games.dir/build
.PHONY : games/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named tests_run

# Build rule for target.
tests_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests_run
.PHONY : tests_run

# fast build rule for target.
tests_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_run.dir/build.make CMakeFiles/tests_run.dir/build
.PHONY : tests_run/fast

library/game_libraries/pacman/Pacman.o: library/game_libraries/pacman/Pacman.cpp.o
.PHONY : library/game_libraries/pacman/Pacman.o

# target to build an object file
library/game_libraries/pacman/Pacman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/library/game_libraries/pacman/Pacman.cpp.o
.PHONY : library/game_libraries/pacman/Pacman.cpp.o

library/game_libraries/pacman/Pacman.i: library/game_libraries/pacman/Pacman.cpp.i
.PHONY : library/game_libraries/pacman/Pacman.i

# target to preprocess a source file
library/game_libraries/pacman/Pacman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/library/game_libraries/pacman/Pacman.cpp.i
.PHONY : library/game_libraries/pacman/Pacman.cpp.i

library/game_libraries/pacman/Pacman.s: library/game_libraries/pacman/Pacman.cpp.s
.PHONY : library/game_libraries/pacman/Pacman.s

# target to generate assembly for a file
library/game_libraries/pacman/Pacman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/library/game_libraries/pacman/Pacman.cpp.s
.PHONY : library/game_libraries/pacman/Pacman.cpp.s

library/game_libraries/snake/Snake.o: library/game_libraries/snake/Snake.cpp.o
.PHONY : library/game_libraries/snake/Snake.o

# target to build an object file
library/game_libraries/snake/Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/library/game_libraries/snake/Snake.cpp.o
.PHONY : library/game_libraries/snake/Snake.cpp.o

library/game_libraries/snake/Snake.i: library/game_libraries/snake/Snake.cpp.i
.PHONY : library/game_libraries/snake/Snake.i

# target to preprocess a source file
library/game_libraries/snake/Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/library/game_libraries/snake/Snake.cpp.i
.PHONY : library/game_libraries/snake/Snake.cpp.i

library/game_libraries/snake/Snake.s: library/game_libraries/snake/Snake.cpp.s
.PHONY : library/game_libraries/snake/Snake.s

# target to generate assembly for a file
library/game_libraries/snake/Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/library/game_libraries/snake/Snake.cpp.s
.PHONY : library/game_libraries/snake/Snake.cpp.s

library/graphic_libraries/ncurses/library_ncurses.o: library/graphic_libraries/ncurses/library_ncurses.cpp.o
.PHONY : library/graphic_libraries/ncurses/library_ncurses.o

# target to build an object file
library/graphic_libraries/ncurses/library_ncurses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/library/graphic_libraries/ncurses/library_ncurses.cpp.o
.PHONY : library/graphic_libraries/ncurses/library_ncurses.cpp.o

library/graphic_libraries/ncurses/library_ncurses.i: library/graphic_libraries/ncurses/library_ncurses.cpp.i
.PHONY : library/graphic_libraries/ncurses/library_ncurses.i

# target to preprocess a source file
library/graphic_libraries/ncurses/library_ncurses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/library/graphic_libraries/ncurses/library_ncurses.cpp.i
.PHONY : library/graphic_libraries/ncurses/library_ncurses.cpp.i

library/graphic_libraries/ncurses/library_ncurses.s: library/graphic_libraries/ncurses/library_ncurses.cpp.s
.PHONY : library/graphic_libraries/ncurses/library_ncurses.s

# target to generate assembly for a file
library/graphic_libraries/ncurses/library_ncurses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncurses.dir/build.make CMakeFiles/ncurses.dir/library/graphic_libraries/ncurses/library_ncurses.cpp.s
.PHONY : library/graphic_libraries/ncurses/library_ncurses.cpp.s

library/graphic_libraries/sdl/library_sdl.o: library/graphic_libraries/sdl/library_sdl.cpp.o
.PHONY : library/graphic_libraries/sdl/library_sdl.o

# target to build an object file
library/graphic_libraries/sdl/library_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl.dir/build.make CMakeFiles/sdl.dir/library/graphic_libraries/sdl/library_sdl.cpp.o
.PHONY : library/graphic_libraries/sdl/library_sdl.cpp.o

library/graphic_libraries/sdl/library_sdl.i: library/graphic_libraries/sdl/library_sdl.cpp.i
.PHONY : library/graphic_libraries/sdl/library_sdl.i

# target to preprocess a source file
library/graphic_libraries/sdl/library_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl.dir/build.make CMakeFiles/sdl.dir/library/graphic_libraries/sdl/library_sdl.cpp.i
.PHONY : library/graphic_libraries/sdl/library_sdl.cpp.i

library/graphic_libraries/sdl/library_sdl.s: library/graphic_libraries/sdl/library_sdl.cpp.s
.PHONY : library/graphic_libraries/sdl/library_sdl.s

# target to generate assembly for a file
library/graphic_libraries/sdl/library_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl.dir/build.make CMakeFiles/sdl.dir/library/graphic_libraries/sdl/library_sdl.cpp.s
.PHONY : library/graphic_libraries/sdl/library_sdl.cpp.s

library/graphic_libraries/sfml/library_sfml.o: library/graphic_libraries/sfml/library_sfml.cpp.o
.PHONY : library/graphic_libraries/sfml/library_sfml.o

# target to build an object file
library/graphic_libraries/sfml/library_sfml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml.dir/build.make CMakeFiles/sfml.dir/library/graphic_libraries/sfml/library_sfml.cpp.o
.PHONY : library/graphic_libraries/sfml/library_sfml.cpp.o

library/graphic_libraries/sfml/library_sfml.i: library/graphic_libraries/sfml/library_sfml.cpp.i
.PHONY : library/graphic_libraries/sfml/library_sfml.i

# target to preprocess a source file
library/graphic_libraries/sfml/library_sfml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml.dir/build.make CMakeFiles/sfml.dir/library/graphic_libraries/sfml/library_sfml.cpp.i
.PHONY : library/graphic_libraries/sfml/library_sfml.cpp.i

library/graphic_libraries/sfml/library_sfml.s: library/graphic_libraries/sfml/library_sfml.cpp.s
.PHONY : library/graphic_libraries/sfml/library_sfml.s

# target to generate assembly for a file
library/graphic_libraries/sfml/library_sfml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfml.dir/build.make CMakeFiles/sfml.dir/library/graphic_libraries/sfml/library_sfml.cpp.s
.PHONY : library/graphic_libraries/sfml/library_sfml.cpp.s

src/CoreClass/Core.o: src/CoreClass/Core.cpp.o
.PHONY : src/CoreClass/Core.o

# target to build an object file
src/CoreClass/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/CoreClass/Core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CoreClass/Core.cpp.o
.PHONY : src/CoreClass/Core.cpp.o

src/CoreClass/Core.i: src/CoreClass/Core.cpp.i
.PHONY : src/CoreClass/Core.i

# target to preprocess a source file
src/CoreClass/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/CoreClass/Core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CoreClass/Core.cpp.i
.PHONY : src/CoreClass/Core.cpp.i

src/CoreClass/Core.s: src/CoreClass/Core.cpp.s
.PHONY : src/CoreClass/Core.s

# target to generate assembly for a file
src/CoreClass/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/CoreClass/Core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/CoreClass/Core.cpp.s
.PHONY : src/CoreClass/Core.cpp.s

src/GameClass/Game.o: src/GameClass/Game.cpp.o
.PHONY : src/GameClass/Game.o

# target to build an object file
src/GameClass/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/GameClass/Game.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GameClass/Game.cpp.o
.PHONY : src/GameClass/Game.cpp.o

src/GameClass/Game.i: src/GameClass/Game.cpp.i
.PHONY : src/GameClass/Game.i

# target to preprocess a source file
src/GameClass/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/GameClass/Game.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GameClass/Game.cpp.i
.PHONY : src/GameClass/Game.cpp.i

src/GameClass/Game.s: src/GameClass/Game.cpp.s
.PHONY : src/GameClass/Game.s

# target to generate assembly for a file
src/GameClass/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/GameClass/Game.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/GameClass/Game.cpp.s
.PHONY : src/GameClass/Game.cpp.s

src/InitClass/Init.o: src/InitClass/Init.cpp.o
.PHONY : src/InitClass/Init.o

# target to build an object file
src/InitClass/Init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/InitClass/Init.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/InitClass/Init.cpp.o
.PHONY : src/InitClass/Init.cpp.o

src/InitClass/Init.i: src/InitClass/Init.cpp.i
.PHONY : src/InitClass/Init.i

# target to preprocess a source file
src/InitClass/Init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/InitClass/Init.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/InitClass/Init.cpp.i
.PHONY : src/InitClass/Init.cpp.i

src/InitClass/Init.s: src/InitClass/Init.cpp.s
.PHONY : src/InitClass/Init.s

# target to generate assembly for a file
src/InitClass/Init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/InitClass/Init.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/InitClass/Init.cpp.s
.PHONY : src/InitClass/Init.cpp.s

src/MenuClass/Menu.o: src/MenuClass/Menu.cpp.o
.PHONY : src/MenuClass/Menu.o

# target to build an object file
src/MenuClass/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/MenuClass/Menu.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/MenuClass/Menu.cpp.o
.PHONY : src/MenuClass/Menu.cpp.o

src/MenuClass/Menu.i: src/MenuClass/Menu.cpp.i
.PHONY : src/MenuClass/Menu.i

# target to preprocess a source file
src/MenuClass/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/MenuClass/Menu.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/MenuClass/Menu.cpp.i
.PHONY : src/MenuClass/Menu.cpp.i

src/MenuClass/Menu.s: src/MenuClass/Menu.cpp.s
.PHONY : src/MenuClass/Menu.s

# target to generate assembly for a file
src/MenuClass/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/MenuClass/Menu.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/MenuClass/Menu.cpp.s
.PHONY : src/MenuClass/Menu.cpp.s

src/ProgramEventsClass/ProgramEvents.o: src/ProgramEventsClass/ProgramEvents.cpp.o
.PHONY : src/ProgramEventsClass/ProgramEvents.o

# target to build an object file
src/ProgramEventsClass/ProgramEvents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/ProgramEventsClass/ProgramEvents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramEventsClass/ProgramEvents.cpp.o
.PHONY : src/ProgramEventsClass/ProgramEvents.cpp.o

src/ProgramEventsClass/ProgramEvents.i: src/ProgramEventsClass/ProgramEvents.cpp.i
.PHONY : src/ProgramEventsClass/ProgramEvents.i

# target to preprocess a source file
src/ProgramEventsClass/ProgramEvents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/ProgramEventsClass/ProgramEvents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramEventsClass/ProgramEvents.cpp.i
.PHONY : src/ProgramEventsClass/ProgramEvents.cpp.i

src/ProgramEventsClass/ProgramEvents.s: src/ProgramEventsClass/ProgramEvents.cpp.s
.PHONY : src/ProgramEventsClass/ProgramEvents.s

# target to generate assembly for a file
src/ProgramEventsClass/ProgramEvents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/ProgramEventsClass/ProgramEvents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/ProgramEventsClass/ProgramEvents.cpp.s
.PHONY : src/ProgramEventsClass/ProgramEvents.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arcade.dir/build.make CMakeFiles/arcade.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/Unit_tests/InitClassTests.o: tests/Unit_tests/InitClassTests.cpp.o
.PHONY : tests/Unit_tests/InitClassTests.o

# target to build an object file
tests/Unit_tests/InitClassTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/Unit_tests/InitClassTests.cpp.o
.PHONY : tests/Unit_tests/InitClassTests.cpp.o

tests/Unit_tests/InitClassTests.i: tests/Unit_tests/InitClassTests.cpp.i
.PHONY : tests/Unit_tests/InitClassTests.i

# target to preprocess a source file
tests/Unit_tests/InitClassTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/Unit_tests/InitClassTests.cpp.i
.PHONY : tests/Unit_tests/InitClassTests.cpp.i

tests/Unit_tests/InitClassTests.s: tests/Unit_tests/InitClassTests.cpp.s
.PHONY : tests/Unit_tests/InitClassTests.s

# target to generate assembly for a file
tests/Unit_tests/InitClassTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/Unit_tests/InitClassTests.cpp.s
.PHONY : tests/Unit_tests/InitClassTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... core"
	@echo "... fclean"
	@echo "... games"
	@echo "... graphicals"
	@echo "... re"
	@echo "... tests_run"
	@echo "... arcade"
	@echo "... ncurses"
	@echo "... pacman"
	@echo "... sdl"
	@echo "... sfml"
	@echo "... snake"
	@echo "... unit_tests"
	@echo "... library/game_libraries/pacman/Pacman.o"
	@echo "... library/game_libraries/pacman/Pacman.i"
	@echo "... library/game_libraries/pacman/Pacman.s"
	@echo "... library/game_libraries/snake/Snake.o"
	@echo "... library/game_libraries/snake/Snake.i"
	@echo "... library/game_libraries/snake/Snake.s"
	@echo "... library/graphic_libraries/ncurses/library_ncurses.o"
	@echo "... library/graphic_libraries/ncurses/library_ncurses.i"
	@echo "... library/graphic_libraries/ncurses/library_ncurses.s"
	@echo "... library/graphic_libraries/sdl/library_sdl.o"
	@echo "... library/graphic_libraries/sdl/library_sdl.i"
	@echo "... library/graphic_libraries/sdl/library_sdl.s"
	@echo "... library/graphic_libraries/sfml/library_sfml.o"
	@echo "... library/graphic_libraries/sfml/library_sfml.i"
	@echo "... library/graphic_libraries/sfml/library_sfml.s"
	@echo "... src/CoreClass/Core.o"
	@echo "... src/CoreClass/Core.i"
	@echo "... src/CoreClass/Core.s"
	@echo "... src/GameClass/Game.o"
	@echo "... src/GameClass/Game.i"
	@echo "... src/GameClass/Game.s"
	@echo "... src/InitClass/Init.o"
	@echo "... src/InitClass/Init.i"
	@echo "... src/InitClass/Init.s"
	@echo "... src/MenuClass/Menu.o"
	@echo "... src/MenuClass/Menu.i"
	@echo "... src/MenuClass/Menu.s"
	@echo "... src/ProgramEventsClass/ProgramEvents.o"
	@echo "... src/ProgramEventsClass/ProgramEvents.i"
	@echo "... src/ProgramEventsClass/ProgramEvents.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/Unit_tests/InitClassTests.o"
	@echo "... tests/Unit_tests/InitClassTests.i"
	@echo "... tests/Unit_tests/InitClassTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

